name: buildLinux

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install libEGL1
        run: sudo apt install libegl1

      - name: Install libxcb-xinerama0
        run: sudo apt install libxcb-xinerama0

#      - name: Install Qt
#        uses: jurplel/install-qt-action@v3
#        with:
#          version: '6.2.*'
#          host: 'linux'
#          target: 'desktop'
#          dir: '${{ github.workspace }}/example/'
#          install-deps: 'true'
#          archives: 'qtbase qtsvg'
#          cache: 'false'
#          cache-key-prefix: 'install-qt-action'
#          setup-python: 'true'
#          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
#          set-env: 'true'
#          tools-only: 'false'
#          aqtversion: '==2.1.*'
#          py7zrversion: '==0.19.*'
#          extra: '--external 7z'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pyinstaller run linux_build_folder
        run: pyinstaller --clean --noconfirm specs/linux_build_folder.spec
      - name: Zip Dist Folder
        uses: thedoctor0/zip-release@0.7.1
        with:
          path: dist/DeutscheBahnReservierungssuche
          filename: DBReservierungsSucheUbuntu.zip
      - name: Store ubuntu build artifact
        uses: actions/upload-artifact@v3
        with:
          name: DBReservierungsSuche-ubuntu
          path: DBReservierungsSucheUbuntu.zip